### ISSUE TITLE
National Snow Model - temp EC2 request

### ISSUE THREAD

**Issue by commanderjcc** [CIROH-UA/CloudInfra#15]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.

Joshua Christensen
jchristensen@ua.edu
"Josh Christensen" on slack
8013613299

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources.

National Snow Model - Snow Covered Area enhancement

**3.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

**Options:**
- EC2
- S3 – public, private, requester pay, bucket name suggestion?
- EBS (Amazon Elastic Block Store)
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
 
EC2 - just a small server that can continuously stream data from a NASA download into the National Snow Model s3 bucket. Preferably Ohio region to avoid extra transfer

**4.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 
Will be completely done by July 28, but likely earlier

**5.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
None

**6.	Budget:** 
Include any budget constraints or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.
 
Something small and cheap will do great. Just needs an internet connection and to be able to run something along the lines of: `curl <any curl parameters as fit> | aws s3 cp - <your s3 bucket/folder> --expected-size <any max size in byte in case the file is larger than 50GB>`
 
**7.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

I have no clue, I'm an REU student. But my advisor is Ryan Johnson and I've discussed it with Arpita

**Comment by arpita0911patel** [comment]
Thank you Josh, also S3 bucket is created as per our discussion for this. It's under AWS UA sub account named "national-snow-model".

**Comment by benlee0423** [comment]
t2.small ( 1 vCPU and 2GB RAM) in ohio region, $0.023 USD per hour
30GB gp2 storage
@commanderjcc  Let me know if above spec works for you.

**Comment by commanderjcc** [comment]
Looks great, thanks

**Comment by benlee0423** [comment]
@commanderjcc Do you also need an aws account to access ec2 instance?

**Comment by harshavemula-ua** [comment]
@commanderjcc  Are you still actively using the resource allocated for this project...Pls do let us know so that we take appropriate actions of resource clean up.
